package com.lottery.api.mapper.dlt;

import com.lottery.api.bean.dlt.Detail;
import org.apache.ibatis.annotations.*;

import java.util.List;

@Mapper
public interface DetailMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_detail
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Select({
            "select",
            "term, money, level, piece, num, allmoney, type",
            "from dlt_detail",
            "where term = #{term,jdbcType=VARCHAR}"
    })
    Detail selectByPrimaryKey(String term);

    @Insert({
            "<script>",
            "insert into dlt_detail (term,money, level,piece, num, allmoney,type) ",
            "values ",
            "<foreach collection=\"list\" item = \"item\"  separator=\",\">",
            "(#{item.term,jdbcType=VARCHAR},#{item.money,jdbcType=VARCHAR}, #{item.level,jdbcType=VARCHAR},#{item.piece,jdbcType=VARCHAR}, #{item.num,jdbcType=VARCHAR}, #{item.allmoney,jdbcType=VARCHAR},#{item.type,jdbcType=CHAR} )",
            "</foreach>",
            "</script>"
    })
    int batchInsert(List<Detail> details);
}