package com.lottery.api.mapper.dlt;

import com.lottery.api.bean.dlt.Detail;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface DetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_detail
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Delete({
        "delete from dlt_detail",
        "where term = #{term,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String term);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_detail
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Insert({
        "insert into dlt_detail (money, level, ",
        "piece, num, allmoney, ",
        "type)",
        "values (#{money,jdbcType=VARCHAR}, #{level,jdbcType=VARCHAR}, ",
        "#{piece,jdbcType=VARCHAR}, #{num,jdbcType=VARCHAR}, #{allmoney,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=CHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="term", before=false, resultType=String.class)
    int insert(Detail record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_detail
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Select({
        "select",
        "term, money, level, piece, num, allmoney, type",
        "from dlt_detail",
        "where term = #{term,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="term", property="term", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="money", property="money", jdbcType=JdbcType.VARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.VARCHAR),
        @Result(column="piece", property="piece", jdbcType=JdbcType.VARCHAR),
        @Result(column="num", property="num", jdbcType=JdbcType.VARCHAR),
        @Result(column="allmoney", property="allmoney", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.CHAR)
    })
    Detail selectByPrimaryKey(String term);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_detail
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Update({
        "update dlt_detail",
        "set money = #{money,jdbcType=VARCHAR},",
          "level = #{level,jdbcType=VARCHAR},",
          "piece = #{piece,jdbcType=VARCHAR},",
          "num = #{num,jdbcType=VARCHAR},",
          "allmoney = #{allmoney,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=CHAR}",
        "where term = #{term,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Detail record);
}