package com.lottery.api.mapper.dlt;

import com.lottery.api.bean.dlt.Lottery;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface LotteryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_lottery
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Delete({
        "delete from dlt_lottery",
        "where term = #{term,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String term);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_lottery
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Insert({
        "insert into dlt_lottery (openTime_fmt1, openTime_fmt, ",
        "numSequence, pool, ",
        "totalSales, number, ",
        "sTime, fTime, totlSaleNews, ",
        "drawNews, isAP, ",
        "number_pool, ispool, ",
        "totalSales2, verify, ",
        "lType, numSequence_pool, ",
        "status)",
        "values (#{opentimeFmt1,jdbcType=VARCHAR}, #{opentimeFmt,jdbcType=VARCHAR}, ",
        "#{numsequence,jdbcType=VARCHAR}, #{pool,jdbcType=VARCHAR}, ",
        "#{totalsales,jdbcType=VARCHAR}, #{number,jdbcType=VARCHAR}, ",
        "#{stime,jdbcType=VARCHAR}, #{ftime,jdbcType=VARCHAR}, #{totlsalenews,jdbcType=VARCHAR}, ",
        "#{drawnews,jdbcType=VARCHAR}, #{isap,jdbcType=INTEGER}, ",
        "#{numberPool,jdbcType=VARCHAR}, #{ispool,jdbcType=INTEGER}, ",
        "#{totalsales2,jdbcType=VARCHAR}, #{verify,jdbcType=INTEGER}, ",
        "#{ltype,jdbcType=INTEGER}, #{numsequencePool,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="term", before=false, resultType=String.class)
    int insert(Lottery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_lottery
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Select({
        "select",
        "term, openTime_fmt1, openTime_fmt, numSequence, pool, totalSales, number, sTime, ",
        "fTime, totlSaleNews, drawNews, isAP, number_pool, ispool, totalSales2, verify, ",
        "lType, numSequence_pool, status",
        "from dlt_lottery",
        "where term = #{term,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="term", property="term", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="openTime_fmt1", property="opentimeFmt1", jdbcType=JdbcType.VARCHAR),
        @Result(column="openTime_fmt", property="opentimeFmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="numSequence", property="numsequence", jdbcType=JdbcType.VARCHAR),
        @Result(column="pool", property="pool", jdbcType=JdbcType.VARCHAR),
        @Result(column="totalSales", property="totalsales", jdbcType=JdbcType.VARCHAR),
        @Result(column="number", property="number", jdbcType=JdbcType.VARCHAR),
        @Result(column="sTime", property="stime", jdbcType=JdbcType.VARCHAR),
        @Result(column="fTime", property="ftime", jdbcType=JdbcType.VARCHAR),
        @Result(column="totlSaleNews", property="totlsalenews", jdbcType=JdbcType.VARCHAR),
        @Result(column="drawNews", property="drawnews", jdbcType=JdbcType.VARCHAR),
        @Result(column="isAP", property="isap", jdbcType=JdbcType.INTEGER),
        @Result(column="number_pool", property="numberPool", jdbcType=JdbcType.VARCHAR),
        @Result(column="ispool", property="ispool", jdbcType=JdbcType.INTEGER),
        @Result(column="totalSales2", property="totalsales2", jdbcType=JdbcType.VARCHAR),
        @Result(column="verify", property="verify", jdbcType=JdbcType.INTEGER),
        @Result(column="lType", property="ltype", jdbcType=JdbcType.INTEGER),
        @Result(column="numSequence_pool", property="numsequencePool", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    Lottery selectByPrimaryKey(String term);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_lottery
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Update({
        "update dlt_lottery",
        "set openTime_fmt1 = #{opentimeFmt1,jdbcType=VARCHAR},",
          "openTime_fmt = #{opentimeFmt,jdbcType=VARCHAR},",
          "numSequence = #{numsequence,jdbcType=VARCHAR},",
          "pool = #{pool,jdbcType=VARCHAR},",
          "totalSales = #{totalsales,jdbcType=VARCHAR},",
          "number = #{number,jdbcType=VARCHAR},",
          "sTime = #{stime,jdbcType=VARCHAR},",
          "fTime = #{ftime,jdbcType=VARCHAR},",
          "totlSaleNews = #{totlsalenews,jdbcType=VARCHAR},",
          "drawNews = #{drawnews,jdbcType=VARCHAR},",
          "isAP = #{isap,jdbcType=INTEGER},",
          "number_pool = #{numberPool,jdbcType=VARCHAR},",
          "ispool = #{ispool,jdbcType=INTEGER},",
          "totalSales2 = #{totalsales2,jdbcType=VARCHAR},",
          "verify = #{verify,jdbcType=INTEGER},",
          "lType = #{ltype,jdbcType=INTEGER},",
          "numSequence_pool = #{numsequencePool,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER}",
        "where term = #{term,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Lottery record);
}