package com.lottery.api.mapper.dlt;

import com.lottery.api.bean.dlt.Lottery;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface LotteryMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_lottery
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Insert({
        "insert into dlt_lottery (term,openTime_fmt1, openTime_fmt, ",
        "numSequence, pool, ",
        "totalSales, number, ",
        "sTime, fTime, totlSaleNews, ",
        "drawNews, isAP, ",
        "number_pool, ispool, ",
        "totalSales2, verify, ",
        "lType, numSequence_pool, ",
        "status)",
        "values (#{term,jdbcType=VARCHAR},#{openTime_fmt1,jdbcType=VARCHAR}, #{openTime_fmt,jdbcType=VARCHAR}, ",
        "#{numSequence,jdbcType=VARCHAR}, #{pool,jdbcType=VARCHAR}, ",
        "#{totalSales,jdbcType=VARCHAR}, #{number,jdbcType=VARCHAR}, ",
        "#{sTime,jdbcType=VARCHAR}, #{fTime,jdbcType=VARCHAR}, #{totlSaleNews,jdbcType=VARCHAR}, ",
        "#{drawNews,jdbcType=VARCHAR}, #{isAP,jdbcType=INTEGER}, ",
        "#{number_pool,jdbcType=VARCHAR}, #{ispool,jdbcType=INTEGER}, ",
        "#{totalSales2,jdbcType=VARCHAR}, #{verify,jdbcType=INTEGER}, ",
        "#{lType,jdbcType=INTEGER}, #{numSequence_pool,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER})"
    })
    int insert(Lottery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_lottery
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Select({
        "select",
        "term, openTime_fmt1, openTime_fmt, numSequence, pool, totalSales, number, sTime, ",
        "fTime, totlSaleNews, drawNews, isAP, number_pool, ispool, totalSales2, verify, ",
        "lType, numSequence_pool, status",
        "from dlt_lottery",
        "where term = #{term,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="term", property="term", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="openTime_fmt1", property="openTime_fmt1", jdbcType=JdbcType.VARCHAR),
        @Result(column="openTime_fmt", property="openTime_fmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="numSequence", property="numSequence", jdbcType=JdbcType.VARCHAR),
        @Result(column="pool", property="pool", jdbcType=JdbcType.VARCHAR),
        @Result(column="totalSales", property="totalSales", jdbcType=JdbcType.VARCHAR),
        @Result(column="number", property="number", jdbcType=JdbcType.VARCHAR),
        @Result(column="sTime", property="sTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="fTime", property="fTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="totlSaleNews", property="totlSaleNews", jdbcType=JdbcType.VARCHAR),
        @Result(column="drawNews", property="drawNews", jdbcType=JdbcType.VARCHAR),
        @Result(column="isAP", property="isAP", jdbcType=JdbcType.INTEGER),
        @Result(column="number_pool", property="number_pool", jdbcType=JdbcType.VARCHAR),
        @Result(column="ispool", property="ispool", jdbcType=JdbcType.INTEGER),
        @Result(column="totalSales2", property="totalSales2", jdbcType=JdbcType.VARCHAR),
        @Result(column="verify", property="verify", jdbcType=JdbcType.INTEGER),
        @Result(column="lType", property="lType", jdbcType=JdbcType.INTEGER),
        @Result(column="numSequence_pool", property="numSequence_pool", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    Lottery selectByPrimaryKey(String term);

}