package com.lottery.api.mapper.dlt;

import com.lottery.api.bean.dlt.OpenTime;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface OpenTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_open_time
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Delete({
        "delete from dlt_open_time",
        "where term = #{term,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String term);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_open_time
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Insert({
        "insert into dlt_open_time (year, month, ",
        "date, hours, minutes, ",
        "seconds, nanos, ",
        "time, day, timezoneOffset)",
        "values (#{year,jdbcType=INTEGER}, #{month,jdbcType=INTEGER}, ",
        "#{date,jdbcType=INTEGER}, #{hours,jdbcType=INTEGER}, #{minutes,jdbcType=INTEGER}, ",
        "#{seconds,jdbcType=INTEGER}, #{nanos,jdbcType=INTEGER}, ",
        "#{time,jdbcType=BIGINT}, #{day,jdbcType=INTEGER}, #{timezoneoffset,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="term", before=false, resultType=String.class)
    int insert(OpenTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_open_time
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Select({
        "select",
        "term, year, month, date, hours, minutes, seconds, nanos, time, day, timezoneOffset",
        "from dlt_open_time",
        "where term = #{term,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="term", property="term", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="year", property="year", jdbcType=JdbcType.INTEGER),
        @Result(column="month", property="month", jdbcType=JdbcType.INTEGER),
        @Result(column="date", property="date", jdbcType=JdbcType.INTEGER),
        @Result(column="hours", property="hours", jdbcType=JdbcType.INTEGER),
        @Result(column="minutes", property="minutes", jdbcType=JdbcType.INTEGER),
        @Result(column="seconds", property="seconds", jdbcType=JdbcType.INTEGER),
        @Result(column="nanos", property="nanos", jdbcType=JdbcType.INTEGER),
        @Result(column="time", property="time", jdbcType=JdbcType.BIGINT),
        @Result(column="day", property="day", jdbcType=JdbcType.INTEGER),
        @Result(column="timezoneOffset", property="timezoneoffset", jdbcType=JdbcType.INTEGER)
    })
    OpenTime selectByPrimaryKey(String term);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlt_open_time
     *
     * @mbg.generated Tue May 14 15:30:54 CST 2019
     */
    @Update({
        "update dlt_open_time",
        "set year = #{year,jdbcType=INTEGER},",
          "month = #{month,jdbcType=INTEGER},",
          "date = #{date,jdbcType=INTEGER},",
          "hours = #{hours,jdbcType=INTEGER},",
          "minutes = #{minutes,jdbcType=INTEGER},",
          "seconds = #{seconds,jdbcType=INTEGER},",
          "nanos = #{nanos,jdbcType=INTEGER},",
          "time = #{time,jdbcType=BIGINT},",
          "day = #{day,jdbcType=INTEGER},",
          "timezoneOffset = #{timezoneoffset,jdbcType=INTEGER}",
        "where term = #{term,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(OpenTime record);
}